bind_to_address            "127.0.0.1"
port                       "6600"

auto_update                "yes"
restore_paused             "yes"

music_directory            "~/Music"
playlist_directory         "~/.config/mpd/playlists"
db_file                    "~/.config/mpd/database"
log_file                   "syslog"
pid_file                   "~/.config/mpd/pid"
state_file                 "~/.config/mpd/state"

audio_output {
    type                   "pipewire"
    name                   "PipeWire Sound Server"
    buffer_time            "100000"
}

audio_output {
	type                     "httpd"
	name                     "lossless"
	encoder                  "flac"
	port                     "8000"
	max_client               "8"
	mixer_type               "software"
	format                   "48000:24:2"
}
