#!/bin/sh

# ╔══════════════════════════════════════════════════════════════════════╗
# ║                       BSPWM Window Rules                             ║
# ╚══════════════════════════════════════════════════════════════════════╝

bspc monitor -d 1 2 3 4 5 6

bspc rule -a TelegramDesktop desktop=^5 private=on locked=on
bspc rule -a Chromium desktop=^4 private=on locked=on
bspc rule -a mpv sticky=on
bspc rule -a '*:*:Picture in picture' state=floating sticky=on border=off rectangle=640x360+1280+720

# ╔══════════════════════════════════════════════════════════════════════╗
# ║                     Start Environment                                ║
# ╚══════════════════════════════════════════════════════════════════════╝

# Hotkey Daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Polybar Daemon
sh ~/.config/polybar/launch.sh --colorblocks &

# Compositor Daemon
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &

# Notify Daemon
pgrep -x dunst >/dev/null || dunst --config ~/.config/dunst/dunstrc &

# Clipboard Daemon
pgrep -x greenclip >/dev/null || greenclip daemon &

# Polkit Daemon
pgrep -x "polkit-gnome-au" >/dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper Daemon
pgrep -x feh >/dev/null || feh --recursive --bg-fill --no-fehbg --randomize ~/Wallpapers/* &

# ╔══════════════════════════════════════════════════════════════════════╗
# ║                       Xorg Settings                                  ║
# ╚══════════════════════════════════════════════════════════════════════╝

# Fix cursor
xsetroot -cursor_name left_ptr

# Set keyboard repeat delay and rate
xset r rate 200 50

# Set resolution
xrandr --output DP-1 --mode 1920x1080 --rate 144

# ╔══════════════════════════════════════════════════════════════════════╗
# ║                       User Settings                                  ║
# ╚══════════════════════════════════════════════════════════════════════╝

# Autorun
sh ~/.local/bin/autorun &

# ╔══════════════════════════════════════════════════════════════════════╗
# ║                     BSPWM General Configuration                      ║
# ╚══════════════════════════════════════════════════════════════════════╝

bspc config border_width 3
bspc config window_gap 3
bspc config split_ratio 0.5

bspc config normal_border_color "#000000"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#ffffff"

bspc config focus_follows_pointer true
bspc config pointer_modifier true
bspc config paddingless_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
